project:
  type: website

website:
  title: "Lumos Insight"
  favicon: "images/logo.PNG"
  sidebar:
    logo: "images/logo.PNG"
    style: "docked"
    search: false
    contents:
      - text: "Posts"
        href: posts.qmd
      - text: "About"
        href: about.qmd
      - text: "Subjects"
        href: subjects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


