project:
  type: website

website:
  title: "Lumos Insight"
  image: "images/logo.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    sidebar:
      logo: "images/logo.png"
      nav:
        - text: "Home"
          href: "index.html"
        - text: "About"
          href: "about.html"


