project:
  type: website

website:
  title: "Lumos Insight"
  description: "Exploring knowledge, measurement, behaviour, and technology"
  site-url: https://www.lumosinsight.co.uk   # enables absolute OG/Twitter URLs
  open-graph: true
  favicon: "images/logo.PNG"
  sidebar:
    logo: "images/logo.PNG"
    style: "docked"
    search: false
    contents:
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Subjects"
        href: subjects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
